# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhlS_ksfvXbmlo6UKDUmDtSokbj0gClR
"""

!pip install faker

import pandas as pd
import numpy as np
from faker import Faker
fake = Faker('es_ES')

n = 5000
especialidades = [
    'Medicina General',
    'Pediatría',
    'Cardiología',
    'Traumatología',
    'Ginecología',
    'Dermatología'
]
estados = [
    'Atendida',
    'Cancelada',
    'No asistió'
]
datos = []
for i in range(n):
    datos.append([
        i+1,
        fake.date_between('-1y','today'),
        np.random.choice(especialidades),
        np.random.choice(estados,p=[0.75,0.15,0.10]),
        np.random.randint(15,90)
    ])
df = pd.DataFrame(datos,
                  columns=[
                      'id_cita',
                      'fecha',
                      'especialidad',
                      'estado',
                      'edad'
                  ])
df.head()

df.to_csv('citas_medicas.csv',index=False)

df = pd.read_csv('citas_medicas.csv')

df.describe()

df['especialidad'].value_counts()

df['estado'].value_counts(normalize=True)*100

df['fecha']=pd.to_datetime(df['fecha'])
df['mes']=df['fecha'].dt.month

from sklearn.linear_model import LinearRegression
import numpy as np

x=np.array(df.groupby('mes').size().index).reshape(-1,1)
y=np.array(df.groupby('mes').size().values)

modelo=LinearRegression()
modelo.fit(x,y)

prediccion=modelo.predict([[13]])
print(prediccion)

!pip install streamlit
import streamlit as st
import pandas as pd
import plotly.express as px

df = pd.read_csv('citas_medicas.csv')

st.title('Dashboard de Gestión de Citas Médicas')

st.subheader('Citas por Especialidad')
fig1 = px.bar(
    df['especialidad'].value_counts(),
    labels={'value':'Cantidad'}
)
st.plotly_chart(fig1)

st.subheader('Estado de las Citas')
fig2 = px.pie(
    df,
    names='estado'
)
st.plotly_chart(fig2)

df['fecha']=pd.to_datetime(df['fecha'])
df['mes']=df['fecha'].dt.month

citas_mes=df.groupby('mes').size().reset_index(name='cantidad')

st.subheader('Citas por Mes')
fig3=px.line(
    citas_mes,
    x='mes',
    y='cantidad',
    markers=True
)
st.plotly_chart(fig3)