# -*- coding: utf-8 -*-
"""App3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nkJhMSZFjS8ww7gL2bVuZewOYH6Q3dk1
"""

import streamlit as st
import pandas as pd
import plotly.express as px

df = pd.read_csv('citas_bigdata.csv')

st.title('Dashboard de Gestión de Citas Médicas')

st.subheader('Citas por Especialidad')
fig1 = px.bar(
    df['Especialidad'].value_counts(),
    labels={'value':'Cantidad'}
)
st.plotly_chart(fig1)

st.subheader('Estado de las Citas')
fig2 = px.pie(
    df,
    names='TipoEvento'
)
st.plotly_chart(fig2)

df['FechaRegistro']=pd.to_datetime(df['FechaRegistro'])
df['mes']=df['FechaRegistro'].dt.month

citas_mes=df.groupby('mes').size().reset_index(name='cantidad')

st.subheader('Citas por Mes')
fig3=px.line(
    citas_mes,
    x='mes',
    y='cantidad',
    markers=True
)
st.plotly_chart(fig3)